// ============================================
// CURRENTS SPORTS MEDIA PLANNER - DATA LAYER
// ============================================

// Simple password - in production, use environment variable
export const APP_PASSWORD = 'currents2026';

// All 210 DMAs
export const DMA_DATA = {
  501: { name: 'New York, NY', state: 'NY' },
  502: { name: 'Binghamton, NY', state: 'NY' },
  503: { name: 'Macon, GA', state: 'GA' },
  504: { name: 'Philadelphia, PA', state: 'PA' },
  505: { name: 'Detroit, MI', state: 'MI' },
  506: { name: 'Boston, MA', state: 'MA' },
  507: { name: 'Savannah, GA', state: 'GA' },
  508: { name: 'Pittsburgh, PA', state: 'PA' },
  509: { name: 'Ft. Wayne, IN', state: 'IN' },
  510: { name: 'Cleveland, OH', state: 'OH' },
  511: { name: 'Washington, DC', state: 'DC' },
  512: { name: 'Baltimore, MD', state: 'MD' },
  513: { name: 'Flint, MI', state: 'MI' },
  514: { name: 'Buffalo, NY', state: 'NY' },
  515: { name: 'Cincinnati, OH', state: 'OH' },
  516: { name: 'Erie, PA', state: 'PA' },
  517: { name: 'Charlotte, NC', state: 'NC' },
  518: { name: 'Greensboro, NC', state: 'NC' },
  519: { name: 'Charleston, SC', state: 'SC' },
  520: { name: 'Augusta, GA', state: 'GA' },
  521: { name: 'Providence, RI', state: 'RI' },
  522: { name: 'Columbus, GA', state: 'GA' },
  523: { name: 'Burlington, VT', state: 'VT' },
  524: { name: 'Atlanta, GA', state: 'GA' },
  525: { name: 'Albany, GA', state: 'GA' },
  526: { name: 'Utica, NY', state: 'NY' },
  527: { name: 'Indianapolis, IN', state: 'IN' },
  528: { name: 'Miami, FL', state: 'FL' },
  529: { name: 'Louisville, KY', state: 'KY' },
  530: { name: 'Tallahassee, FL', state: 'FL' },
  531: { name: 'Tri-Cities, TN', state: 'TN' },
  532: { name: 'Albany, NY', state: 'NY' },
  533: { name: 'Hartford, CT', state: 'CT' },
  534: { name: 'Orlando, FL', state: 'FL' },
  535: { name: 'Columbus, OH', state: 'OH' },
  536: { name: 'Youngstown, OH', state: 'OH' },
  537: { name: 'Bangor, ME', state: 'ME' },
  538: { name: 'Rochester, NY', state: 'NY' },
  539: { name: 'Tampa, FL', state: 'FL' },
  540: { name: 'Traverse City, MI', state: 'MI' },
  541: { name: 'Lexington, KY', state: 'KY' },
  542: { name: 'Dayton, OH', state: 'OH' },
  543: { name: 'Springfield, MA', state: 'MA' },
  544: { name: 'Norfolk, VA', state: 'VA' },
  545: { name: 'Greenville, NC', state: 'NC' },
  546: { name: 'Columbia, SC', state: 'SC' },
  547: { name: 'Toledo, OH', state: 'OH' },
  548: { name: 'West Palm Beach, FL', state: 'FL' },
  549: { name: 'Watertown, NY', state: 'NY' },
  550: { name: 'Wilmington, NC', state: 'NC' },
  551: { name: 'Lansing, MI', state: 'MI' },
  552: { name: 'Presque Isle, ME', state: 'ME' },
  553: { name: 'Marquette, MI', state: 'MI' },
  554: { name: 'Wheeling, WV', state: 'WV' },
  555: { name: 'Syracuse, NY', state: 'NY' },
  556: { name: 'Richmond, VA', state: 'VA' },
  557: { name: 'Knoxville, TN', state: 'TN' },
  558: { name: 'Lima, OH', state: 'OH' },
  559: { name: 'Bluefield, WV', state: 'WV' },
  560: { name: 'Raleigh-Durham, NC', state: 'NC' },
  561: { name: 'Jacksonville, FL', state: 'FL' },
  563: { name: 'Grand Rapids, MI', state: 'MI' },
  564: { name: 'Charleston, WV', state: 'WV' },
  565: { name: 'Elmira, NY', state: 'NY' },
  566: { name: 'Harrisburg, PA', state: 'PA' },
  567: { name: 'Greenville, SC', state: 'SC' },
  569: { name: 'Harrisonburg, VA', state: 'VA' },
  570: { name: 'Myrtle Beach, SC', state: 'SC' },
  571: { name: 'Ft. Myers, FL', state: 'FL' },
  573: { name: 'Roanoke, VA', state: 'VA' },
  574: { name: 'Johnstown, PA', state: 'PA' },
  575: { name: 'Chattanooga, TN', state: 'TN' },
  576: { name: 'Salisbury, MD', state: 'MD' },
  577: { name: 'Wilkes-Barre, PA', state: 'PA' },
  581: { name: 'Terre Haute, IN', state: 'IN' },
  582: { name: 'Lafayette, IN', state: 'IN' },
  583: { name: 'Alpena, MI', state: 'MI' },
  584: { name: 'Charlottesville, VA', state: 'VA' },
  588: { name: 'South Bend, IN', state: 'IN' },
  592: { name: 'Gainesville, FL', state: 'FL' },
  596: { name: 'Zanesville, OH', state: 'OH' },
  597: { name: 'Parkersburg, WV', state: 'WV' },
  598: { name: 'Clarksburg, WV', state: 'WV' },
  600: { name: 'Corpus Christi, TX', state: 'TX' },
  602: { name: 'Chicago, IL', state: 'IL' },
  603: { name: 'Joplin, MO', state: 'MO' },
  604: { name: 'Columbia, MO', state: 'MO' },
  605: { name: 'Topeka, KS', state: 'KS' },
  606: { name: 'Dothan, AL', state: 'AL' },
  609: { name: 'St. Louis, MO', state: 'MO' },
  610: { name: 'Rockford, IL', state: 'IL' },
  611: { name: 'Rochester, MN', state: 'MN' },
  612: { name: 'Shreveport, LA', state: 'LA' },
  613: { name: 'Minneapolis, MN', state: 'MN' },
  616: { name: 'Kansas City, MO', state: 'MO' },
  617: { name: 'Milwaukee, WI', state: 'WI' },
  618: { name: 'Houston, TX', state: 'TX' },
  619: { name: 'Springfield, MO', state: 'MO' },
  622: { name: 'New Orleans, LA', state: 'LA' },
  623: { name: 'Dallas-Ft. Worth, TX', state: 'TX' },
  624: { name: 'Sioux City, IA', state: 'IA' },
  625: { name: 'Waco, TX', state: 'TX' },
  626: { name: 'Victoria, TX', state: 'TX' },
  627: { name: 'Wichita Falls, TX', state: 'TX' },
  628: { name: 'Monroe, LA', state: 'LA' },
  630: { name: 'Birmingham, AL', state: 'AL' },
  631: { name: 'Ottumwa, IA', state: 'IA' },
  632: { name: 'Paducah, KY', state: 'KY' },
  633: { name: 'Odessa, TX', state: 'TX' },
  634: { name: 'Amarillo, TX', state: 'TX' },
  635: { name: 'Austin, TX', state: 'TX' },
  636: { name: 'Harlingen, TX', state: 'TX' },
  637: { name: 'Cedar Rapids, IA', state: 'IA' },
  638: { name: 'St. Joseph, MO', state: 'MO' },
  639: { name: 'Jackson, TN', state: 'TN' },
  640: { name: 'Memphis, TN', state: 'TN' },
  641: { name: 'San Antonio, TX', state: 'TX' },
  642: { name: 'Lafayette, LA', state: 'LA' },
  643: { name: 'Lake Charles, LA', state: 'LA' },
  644: { name: 'Alexandria, LA', state: 'LA' },
  647: { name: 'Greenwood, MS', state: 'MS' },
  648: { name: 'Champaign, IL', state: 'IL' },
  649: { name: 'Evansville, IN', state: 'IN' },
  650: { name: 'Oklahoma City, OK', state: 'OK' },
  651: { name: 'Lubbock, TX', state: 'TX' },
  652: { name: 'Omaha, NE', state: 'NE' },
  656: { name: 'Panama City, FL', state: 'FL' },
  657: { name: 'Sherman, TX', state: 'TX' },
  658: { name: 'Green Bay, WI', state: 'WI' },
  659: { name: 'Nashville, TN', state: 'TN' },
  661: { name: 'San Angelo, TX', state: 'TX' },
  662: { name: 'Abilene, TX', state: 'TX' },
  669: { name: 'Madison, WI', state: 'WI' },
  670: { name: 'Ft. Smith, AR', state: 'AR' },
  671: { name: 'Tulsa, OK', state: 'OK' },
  673: { name: 'Columbus, MS', state: 'MS' },
  675: { name: 'Peoria, IL', state: 'IL' },
  676: { name: 'Duluth, MN', state: 'MN' },
  678: { name: 'Wichita, KS', state: 'KS' },
  679: { name: 'Des Moines, IA', state: 'IA' },
  682: { name: 'Davenport, IA', state: 'IA' },
  686: { name: 'Mobile, AL', state: 'AL' },
  687: { name: 'Minot, ND', state: 'ND' },
  691: { name: 'Huntsville, AL', state: 'AL' },
  692: { name: 'Beaumont, TX', state: 'TX' },
  693: { name: 'Little Rock, AR', state: 'AR' },
  698: { name: 'Montgomery, AL', state: 'AL' },
  702: { name: 'La Crosse, WI', state: 'WI' },
  705: { name: 'Wausau, WI', state: 'WI' },
  709: { name: 'Tyler, TX', state: 'TX' },
  710: { name: 'Hattiesburg, MS', state: 'MS' },
  711: { name: 'Meridian, MS', state: 'MS' },
  716: { name: 'Baton Rouge, LA', state: 'LA' },
  717: { name: 'Quincy, IL', state: 'IL' },
  718: { name: 'Jackson, MS', state: 'MS' },
  722: { name: 'Lincoln, NE', state: 'NE' },
  724: { name: 'Fargo, ND', state: 'ND' },
  725: { name: 'Sioux Falls, SD', state: 'SD' },
  734: { name: 'Jonesboro, AR', state: 'AR' },
  736: { name: 'Bowling Green, KY', state: 'KY' },
  737: { name: 'Mankato, MN', state: 'MN' },
  740: { name: 'North Platte, NE', state: 'NE' },
  743: { name: 'Anchorage, AK', state: 'AK' },
  744: { name: 'Honolulu, HI', state: 'HI' },
  745: { name: 'Fairbanks, AK', state: 'AK' },
  746: { name: 'Biloxi, MS', state: 'MS' },
  747: { name: 'Juneau, AK', state: 'AK' },
  749: { name: 'Laredo, TX', state: 'TX' },
  751: { name: 'Denver, CO', state: 'CO' },
  752: { name: 'Colorado Springs, CO', state: 'CO' },
  753: { name: 'Phoenix, AZ', state: 'AZ' },
  754: { name: 'Butte, MT', state: 'MT' },
  755: { name: 'Great Falls, MT', state: 'MT' },
  756: { name: 'Billings, MT', state: 'MT' },
  757: { name: 'Boise, ID', state: 'ID' },
  758: { name: 'Idaho Falls, ID', state: 'ID' },
  759: { name: 'Cheyenne, WY', state: 'WY' },
  760: { name: 'Twin Falls, ID', state: 'ID' },
  762: { name: 'Missoula, MT', state: 'MT' },
  764: { name: 'Rapid City, SD', state: 'SD' },
  765: { name: 'El Paso, TX', state: 'TX' },
  766: { name: 'Helena, MT', state: 'MT' },
  767: { name: 'Casper, WY', state: 'WY' },
  770: { name: 'Salt Lake City, UT', state: 'UT' },
  771: { name: 'Yuma, AZ', state: 'AZ' },
  773: { name: 'Grand Junction, CO', state: 'CO' },
  789: { name: 'Tucson, AZ', state: 'AZ' },
  790: { name: 'Albuquerque, NM', state: 'NM' },
  798: { name: 'Glendive, MT', state: 'MT' },
  800: { name: 'Bakersfield, CA', state: 'CA' },
  801: { name: 'Eugene, OR', state: 'OR' },
  802: { name: 'Eureka, CA', state: 'CA' },
  803: { name: 'Los Angeles, CA', state: 'CA' },
  804: { name: 'Palm Springs, CA', state: 'CA' },
  807: { name: 'San Francisco, CA', state: 'CA' },
  810: { name: 'Yakima, WA', state: 'WA' },
  811: { name: 'Reno, NV', state: 'NV' },
  813: { name: 'Medford, OR', state: 'OR' },
  819: { name: 'Seattle, WA', state: 'WA' },
  820: { name: 'Portland, OR', state: 'OR' },
  821: { name: 'Bend, OR', state: 'OR' },
  825: { name: 'San Diego, CA', state: 'CA' },
  828: { name: 'Monterey, CA', state: 'CA' },
  839: { name: 'Las Vegas, NV', state: 'NV' },
  855: { name: 'Santa Barbara, CA', state: 'CA' },
  862: { name: 'Sacramento, CA', state: 'CA' },
  866: { name: 'Fresno, CA', state: 'CA' },
  868: { name: 'Chico, CA', state: 'CA' },
  881: { name: 'Spokane, WA', state: 'WA' }
};

// US States
export const US_STATES = [
  { code: 'AL', name: 'Alabama' }, { code: 'AK', name: 'Alaska' }, { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' }, { code: 'CA', name: 'California' }, { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' }, { code: 'DE', name: 'Delaware' }, { code: 'DC', name: 'District of Columbia' },
  { code: 'FL', name: 'Florida' }, { code: 'GA', name: 'Georgia' }, { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' }, { code: 'IL', name: 'Illinois' }, { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' }, { code: 'KS', name: 'Kansas' }, { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' }, { code: 'ME', name: 'Maine' }, { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' }, { code: 'MI', name: 'Michigan' }, { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' }, { code: 'MO', name: 'Missouri' }, { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' }, { code: 'NV', name: 'Nevada' }, { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' }, { code: 'NM', name: 'New Mexico' }, { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' }, { code: 'ND', name: 'North Dakota' }, { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' }, { code: 'OR', name: 'Oregon' }, { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' }, { code: 'SC', name: 'South Carolina' }, { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' }, { code: 'TX', name: 'Texas' }, { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' }, { code: 'VA', name: 'Virginia' }, { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' }, { code: 'WI', name: 'Wisconsin' }, { code: 'WY', name: 'Wyoming' }
];

// Teams data
export const TEAMS_DATA = {
  nfl: [
    { id: 'ARI', name: 'Arizona Cardinals', league: 'NFL' },
    { id: 'ATL', name: 'Atlanta Falcons', league: 'NFL' },
    { id: 'BAL', name: 'Baltimore Ravens', league: 'NFL' },
    { id: 'BUF', name: 'Buffalo Bills', league: 'NFL' },
    { id: 'CAR', name: 'Carolina Panthers', league: 'NFL' },
    { id: 'CHI', name: 'Chicago Bears', league: 'NFL' },
    { id: 'CIN', name: 'Cincinnati Bengals', league: 'NFL' },
    { id: 'CLE', name: 'Cleveland Browns', league: 'NFL' },
    { id: 'DAL', name: 'Dallas Cowboys', league: 'NFL' },
    { id: 'DEN', name: 'Denver Broncos', league: 'NFL' },
    { id: 'DET', name: 'Detroit Lions', league: 'NFL' },
    { id: 'GB', name: 'Green Bay Packers', league: 'NFL' },
    { id: 'HOU', name: 'Houston Texans', league: 'NFL' },
    { id: 'IND', name: 'Indianapolis Colts', league: 'NFL' },
    { id: 'JAX', name: 'Jacksonville Jaguars', league: 'NFL' },
    { id: 'KC', name: 'Kansas City Chiefs', league: 'NFL' },
    { id: 'LV', name: 'Las Vegas Raiders', league: 'NFL' },
    { id: 'LAC', name: 'Los Angeles Chargers', league: 'NFL' },
    { id: 'LAR', name: 'Los Angeles Rams', league: 'NFL' },
    { id: 'MIA', name: 'Miami Dolphins', league: 'NFL' },
    { id: 'MIN', name: 'Minnesota Vikings', league: 'NFL' },
    { id: 'NE', name: 'New England Patriots', league: 'NFL' },
    { id: 'NO', name: 'New Orleans Saints', league: 'NFL' },
    { id: 'NYG', name: 'New York Giants', league: 'NFL' },
    { id: 'NYJ', name: 'New York Jets', league: 'NFL' },
    { id: 'PHI', name: 'Philadelphia Eagles', league: 'NFL' },
    { id: 'PIT', name: 'Pittsburgh Steelers', league: 'NFL' },
    { id: 'SF', name: 'San Francisco 49ers', league: 'NFL' },
    { id: 'SEA', name: 'Seattle Seahawks', league: 'NFL' },
    { id: 'TB', name: 'Tampa Bay Buccaneers', league: 'NFL' },
    { id: 'TEN', name: 'Tennessee Titans', league: 'NFL' },
    { id: 'WAS', name: 'Washington Commanders', league: 'NFL' }
  ],
  nba: [
    { id: 'ATL', name: 'Atlanta Hawks', league: 'NBA' },
    { id: 'BOS', name: 'Boston Celtics', league: 'NBA' },
    { id: 'BKN', name: 'Brooklyn Nets', league: 'NBA' },
    { id: 'CHA', name: 'Charlotte Hornets', league: 'NBA' },
    { id: 'CHI', name: 'Chicago Bulls', league: 'NBA' },
    { id: 'CLE', name: 'Cleveland Cavaliers', league: 'NBA' },
    { id: 'DAL', name: 'Dallas Mavericks', league: 'NBA' },
    { id: 'DEN', name: 'Denver Nuggets', league: 'NBA' },
    { id: 'DET', name: 'Detroit Pistons', league: 'NBA' },
    { id: 'GSW', name: 'Golden State Warriors', league: 'NBA' },
    { id: 'HOU', name: 'Houston Rockets', league: 'NBA' },
    { id: 'IND', name: 'Indiana Pacers', league: 'NBA' },
    { id: 'LAC', name: 'Los Angeles Clippers', league: 'NBA' },
    { id: 'LAL', name: 'Los Angeles Lakers', league: 'NBA' },
    { id: 'MEM', name: 'Memphis Grizzlies', league: 'NBA' },
    { id: 'MIA', name: 'Miami Heat', league: 'NBA' },
    { id: 'MIL', name: 'Milwaukee Bucks', league: 'NBA' },
    { id: 'MIN', name: 'Minnesota Timberwolves', league: 'NBA' },
    { id: 'NOP', name: 'New Orleans Pelicans', league: 'NBA' },
    { id: 'NYK', name: 'New York Knicks', league: 'NBA' },
    { id: 'OKC', name: 'Oklahoma City Thunder', league: 'NBA' },
    { id: 'ORL', name: 'Orlando Magic', league: 'NBA' },
    { id: 'PHI', name: 'Philadelphia 76ers', league: 'NBA' },
    { id: 'PHX', name: 'Phoenix Suns', league: 'NBA' },
    { id: 'POR', name: 'Portland Trail Blazers', league: 'NBA' },
    { id: 'SAC', name: 'Sacramento Kings', league: 'NBA' },
    { id: 'SAS', name: 'San Antonio Spurs', league: 'NBA' },
    { id: 'TOR', name: 'Toronto Raptors', league: 'NBA' },
    { id: 'UTA', name: 'Utah Jazz', league: 'NBA' },
    { id: 'WAS', name: 'Washington Wizards', league: 'NBA' }
  ],
  mlb: [
    { id: 'ARI', name: 'Arizona Diamondbacks', league: 'MLB' },
    { id: 'ATL', name: 'Atlanta Braves', league: 'MLB' },
    { id: 'BAL', name: 'Baltimore Orioles', league: 'MLB' },
    { id: 'BOS', name: 'Boston Red Sox', league: 'MLB' },
    { id: 'CHC', name: 'Chicago Cubs', league: 'MLB' },
    { id: 'CWS', name: 'Chicago White Sox', league: 'MLB' },
    { id: 'CIN', name: 'Cincinnati Reds', league: 'MLB' },
    { id: 'CLE', name: 'Cleveland Guardians', league: 'MLB' },
    { id: 'COL', name: 'Colorado Rockies', league: 'MLB' },
    { id: 'DET', name: 'Detroit Tigers', league: 'MLB' },
    { id: 'HOU', name: 'Houston Astros', league: 'MLB' },
    { id: 'KC', name: 'Kansas City Royals', league: 'MLB' },
    { id: 'LAA', name: 'Los Angeles Angels', league: 'MLB' },
    { id: 'LAD', name: 'Los Angeles Dodgers', league: 'MLB' },
    { id: 'MIA', name: 'Miami Marlins', league: 'MLB' },
    { id: 'MIL', name: 'Milwaukee Brewers', league: 'MLB' },
    { id: 'MIN', name: 'Minnesota Twins', league: 'MLB' },
    { id: 'NYM', name: 'New York Mets', league: 'MLB' },
    { id: 'NYY', name: 'New York Yankees', league: 'MLB' },
    { id: 'OAK', name: 'Oakland Athletics', league: 'MLB' },
    { id: 'PHI', name: 'Philadelphia Phillies', league: 'MLB' },
    { id: 'PIT', name: 'Pittsburgh Pirates', league: 'MLB' },
    { id: 'SD', name: 'San Diego Padres', league: 'MLB' },
    { id: 'SF', name: 'San Francisco Giants', league: 'MLB' },
    { id: 'SEA', name: 'Seattle Mariners', league: 'MLB' },
    { id: 'STL', name: 'St. Louis Cardinals', league: 'MLB' },
    { id: 'TB', name: 'Tampa Bay Rays', league: 'MLB' },
    { id: 'TEX', name: 'Texas Rangers', league: 'MLB' },
    { id: 'TOR', name: 'Toronto Blue Jays', league: 'MLB' },
    { id: 'WAS', name: 'Washington Nationals', league: 'MLB' }
  ],
  nhl: [
    { id: 'ANA', name: 'Anaheim Ducks', league: 'NHL' },
    { id: 'BOS', name: 'Boston Bruins', league: 'NHL' },
    { id: 'BUF', name: 'Buffalo Sabres', league: 'NHL' },
    { id: 'CGY', name: 'Calgary Flames', league: 'NHL' },
    { id: 'CAR', name: 'Carolina Hurricanes', league: 'NHL' },
    { id: 'CHI', name: 'Chicago Blackhawks', league: 'NHL' },
    { id: 'COL', name: 'Colorado Avalanche', league: 'NHL' },
    { id: 'CBJ', name: 'Columbus Blue Jackets', league: 'NHL' },
    { id: 'DAL', name: 'Dallas Stars', league: 'NHL' },
    { id: 'DET', name: 'Detroit Red Wings', league: 'NHL' },
    { id: 'EDM', name: 'Edmonton Oilers', league: 'NHL' },
    { id: 'FLA', name: 'Florida Panthers', league: 'NHL' },
    { id: 'LA', name: 'Los Angeles Kings', league: 'NHL' },
    { id: 'MIN', name: 'Minnesota Wild', league: 'NHL' },
    { id: 'MTL', name: 'Montreal Canadiens', league: 'NHL' },
    { id: 'NSH', name: 'Nashville Predators', league: 'NHL' },
    { id: 'NJ', name: 'New Jersey Devils', league: 'NHL' },
    { id: 'NYI', name: 'New York Islanders', league: 'NHL' },
    { id: 'NYR', name: 'New York Rangers', league: 'NHL' },
    { id: 'OTT', name: 'Ottawa Senators', league: 'NHL' },
    { id: 'PHI', name: 'Philadelphia Flyers', league: 'NHL' },
    { id: 'PIT', name: 'Pittsburgh Penguins', league: 'NHL' },
    { id: 'SJ', name: 'San Jose Sharks', league: 'NHL' },
    { id: 'SEA', name: 'Seattle Kraken', league: 'NHL' },
    { id: 'STL', name: 'St. Louis Blues', league: 'NHL' },
    { id: 'TB', name: 'Tampa Bay Lightning', league: 'NHL' },
    { id: 'TOR', name: 'Toronto Maple Leafs', league: 'NHL' },
    { id: 'UTA', name: 'Utah Hockey Club', league: 'NHL' },
    { id: 'VAN', name: 'Vancouver Canucks', league: 'NHL' },
    { id: 'VGK', name: 'Vegas Golden Knights', league: 'NHL' },
    { id: 'WAS', name: 'Washington Capitals', league: 'NHL' },
    { id: 'WPG', name: 'Winnipeg Jets', league: 'NHL' }
  ]
};

// League API paths for ESPN
export const LEAGUE_API_PATHS = {
  NFL: 'football/nfl',
  NBA: 'basketball/nba',
  MLB: 'baseball/mlb',
  NHL: 'hockey/nhl'
};

// Streaming platforms data
export const STREAMING_PLATFORMS = {
  'ESPN': { streamers: ['ESPN+', 'YouTube TV', 'Hulu + Live TV', 'fuboTV', 'Sling TV'], adSupported: true },
  'ESPN2': { streamers: ['ESPN+', 'YouTube TV', 'Hulu + Live TV', 'fuboTV', 'Sling TV'], adSupported: true },
  'ABC': { streamers: ['ESPN+', 'Hulu', 'YouTube TV', 'Hulu + Live TV'], adSupported: true },
  'FOX': { streamers: ['Fox Sports+', 'Tubi', 'YouTube TV', 'Hulu + Live TV', 'fuboTV'], adSupported: true },
  'FS1': { streamers: ['Fox Sports+', 'YouTube TV', 'Hulu + Live TV', 'fuboTV', 'Sling TV'], adSupported: true },
  'CBS': { streamers: ['Paramount+', 'YouTube TV', 'Hulu + Live TV', 'fuboTV'], adSupported: true },
  'NBC': { streamers: ['Peacock', 'YouTube TV', 'Hulu + Live TV', 'fuboTV'], adSupported: true },
  'TNT': { streamers: ['Max', 'YouTube TV', 'Hulu + Live TV', 'Sling TV'], adSupported: true },
  'TBS': { streamers: ['Max', 'YouTube TV', 'Hulu + Live TV', 'Sling TV'], adSupported: true },
  'Prime Video': { streamers: ['Prime Video'], adSupported: true, isDirectStreamer: true },
  'Peacock': { streamers: ['Peacock'], adSupported: true, isDirectStreamer: true },
  'Netflix': { streamers: ['Netflix'], adSupported: true, isDirectStreamer: true },
  'Apple TV+': { streamers: ['Apple TV+'], adSupported: false, isDirectStreamer: true },
  'ESPN+': { streamers: ['ESPN+'], adSupported: true, isDirectStreamer: true },
  'NBA TV': { streamers: ['NBA League Pass', 'Sling TV', 'fuboTV', 'YouTube TV'], adSupported: true },
  'MLB Network': { streamers: ['MLB.TV', 'Sling TV', 'fuboTV', 'YouTube TV'], adSupported: true },
  'NHL Network': { streamers: ['ESPN+', 'Sling TV', 'fuboTV'], adSupported: true },
  'NFL Network': { streamers: ['NFL+', 'Sling TV', 'fuboTV', 'YouTube TV'], adSupported: true }
};

// Default vendor data structure
export const DEFAULT_VENDOR_DATA = {
  platforms: {
    'ESPN+': { vendors: ['Zeta', 'Statara'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'YouTube TV': { vendors: ['Zeta'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Hulu + Live TV': { vendors: ['Statara'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Peacock': { vendors: ['Zeta', 'Buying Time'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Paramount+': { vendors: ['Statara'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Max': { vendors: ['Zeta'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Prime Video': { vendors: ['Buying Time'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'fuboTV': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Sling TV': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Fox Sports+': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Tubi': { vendors: ['Zeta'], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Netflix': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'Apple TV+': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'NBA League Pass': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'MLB.TV': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' },
    'NFL+': { vendors: [], netCPM: null, grossCPM: null, lastUpdated: null, notes: '' }
  }
};
